export const AllQuestions = {
    htmlCssQuestions: [
        { id: 1, question: "What does HTML stand for?", options: ["HyperText Markup Language", "HighText Machine Language", "Hyperlink and Text Markup Language", "None of these"], answer: "HyperText Markup Language", },
        { id: 2, question: "Which tag is used to create a hyperlink in HTML?", options: ["<a>", "<link>", "<href>", "<hyper>"], answer: "<a>", },
        { id: 3, question: "Which CSS property controls the text size?", options: ["font-style", "text-size", "font-size", "text-style"], answer: "font-size", },
        { id: 4, question: "Which tag is used to insert an image in HTML?", options: ["<image>", "<img>", "<pic>", "<src>"], answer: "<img>", },
        { id: 5, question: "How do you apply a background color in CSS?", options: ["color-background", "background-color", "bgcolor", "set-background"], answer: "background-color", },
        { id: 6, question: "What is the default position of an HTML element?", options: ["static", "relative", "absolute", "fixed"], answer: "static", },
        { id: 7, question: "Which tag is used for the largest heading in HTML?", options: ["<h1>", "<heading>", "<h6>", "<head>"], answer: "<h1>", },
        { id: 8, question: "How do you make text bold in HTML?", options: ["<strong>", "<b>", "<bold>", "Both A and B"], answer: "Both A and B", },
        { id: 9, question: "Which selector is used to select an element by ID in CSS?", options: [".id", "#id", "*id", "$id"], answer: "#id", },
        { id: 10, question: "Which CSS property is used to make rounded borders?", options: ["border-style", "border-radius", "border-shape", "border-round"], answer: "border-radius", },
    ],
    reactQuestions: [
        { id: 1, question: "What is React primarily used for?", options: ["Styling", "Backend", "User Interfaces", "Database"], answer: "User Interfaces", },
        { id: 2, question: "What is the command to create a new React app?", options: ["npx create-app myApp", "npm install react", "npx create-react-app myApp", "react new myApp"], answer: "npx create-react-app myApp", },
        { id: 3, question: "What is a component in React?", options: ["Function", "Class", "Reusable UI element", "Variable"], answer: "Reusable UI element", },
        { id: 4, question: "Which hook is used to manage state in a functional component?", options: ["useRef", "useState", "useEffect", "useReducer"], answer: "useState", },
        { id: 5, question: "What does JSX stand for?", options: ["JavaScript XML", "Java Syntax Extension", "JSON XML", "None"], answer: "JavaScript XML", },
        { id: 6, question: "Which keyword is used to export a component?", options: ["share", "return", "module", "export"], answer: "export", },
        { id: 7, question: "Which hook is used to perform side effects?", options: ["useEffect", "useState", "useMemo", "useReducer"], answer: "useEffect", },
        { id: 8, question: "React is maintained by which company?", options: ["Google", "Microsoft", "Facebook", "Apple"], answer: "Facebook", },
        {
            id: 9, question: "What is returned by a React component?", options: ["Object", "Number", "JSX", "HTML"],
            answer: "JSX",
        },
        { id: 10, question: "How do you pass data to a child component?", options: ["props", "state", "context", "functions"], answer: "props", },
    ],
    jsQuestions: [
        { id: 1, question: "What is used to declare a variable in JavaScript?", options: ["var", "let", "const", "All of the above"], answer: "All of the above", },
        { id: 2, question: "Which method converts JSON to a JavaScript object?", options: ["JSON.parse()", "JSON.stringify()", "JSON.convert()", "JSON.toObject()"], answer: "JSON.parse()", },
        { id: 3, question: "Which symbol is used for comments in JavaScript?", options: ["//", "/* */", "#", "Both A and B"], answer: "Both A and B", },
        { id: 4, question: "How do you write a function in JavaScript?", options: ["function = myFunc()", "function myFunc()", "def myFunc()", "func myFunc()"], answer: "function myFunc()", },
        { id: 5, question: "What does '===' mean in JavaScript?", options: ["Assignment", "Equal in value and type", "Equal in value only", "None"], answer: "Equal in value and type", },
        { id: 6, question: "What is the output of 'typeof null'?", options: ["null", "object", "undefined", "boolean"], answer: "object", },
        { id: 7, question: "Which method is used to add an element to the end of an array?", options: ["push()", "pop()", "shift()", "unshift()"], answer: "push()", },
        { id: 8, question: "What will `2 + '2'` return?", options: ["4", "'4'", "'22'", "NaN"], answer: "'22'", },
        { id: 9, question: "Which keyword stops the loop?", options: ["stop", "exit", "break", "halt"], answer: "break", },
        { id: 10, question: "How do you define an arrow function?", options: ["() => {}", "=> () {}", "() -> {}", "function => {}"], answer: "() => {}", },
    ],
    mathQuestions: [
        { id: 1, question: "What is 8 * 7?", options: ["54", "56", "58", "60"], answer: "56", },
        { id: 2, question: "What is the square root of 81?", options: ["7", "8", "9", "10"], answer: "9", },
        { id: 3, question: "What is 15% of 200?", options: ["25", "30", "35", "40"], answer: "30", },
        { id: 4, question: "Solve: 3² + 4²", options: ["9", "25", "16", "12"], answer: "25", },
        { id: 5, question: "What is 100 divided by 4?", options: ["20", "25", "30", "40"], answer: "25", },
        { id: 6, question: "What is the value of π (up to 2 decimal places)?", options: ["3.14", "3.41", "3.13", "3.15"], answer: "3.14", },
        { id: 7, question: "What comes next: 2, 4, 8, 16, ___?", options: ["18", "24", "32", "20"], answer: "32", },
        { id: 8, question: "How many degrees in a right angle?", options: ["45", "60", "90", "120"], answer: "90", },
        { id: 9, question: "What is the perimeter of a square with side 5 cm?", options: ["10 cm", "15 cm", "20 cm", "25 cm"], answer: "20 cm", },
        { id: 10, question: "What is 0 divided by any number?", options: ["Infinity", "Undefined", "0", "1"], answer: "0", },
    ],
    scienceQuestions: [
        { id: 1, question: "Which gas is essential for breathing?", options: ["Nitrogen", "Carbon Dioxide", "Oxygen", "Helium"], answer: "Oxygen", },
        { id: 2, question: "What is H₂O commonly known as?", options: ["Oxygen", "Water", "Hydrogen", "Salt"], answer: "Water", },
        { id: 3, question: "Which organ pumps blood in the human body?", options: ["Lungs", "Liver", "Heart", "Brain"], answer: "Heart", },
        { id: 4, question: "Which planet is known as the Red Planet?", options: ["Earth", "Mars", "Venus", "Jupiter"], answer: "Mars", },
        { id: 5, question: "What causes day and night?", options: ["Sun's movement", "Earth's rotation", "Moon's rotation", "Clouds"], answer: "Earth's rotation", },
        { id: 6, question: "Which vitamin is made by sunlight?", options: ["Vitamin A", "Vitamin B", "Vitamin D", "Vitamin C"], answer: "Vitamin D", },
        { id: 7, question: "Which part of plant conducts photosynthesis?", options: ["Root", "Stem", "Leaf", "Flower"], answer: "Leaf", },
        { id: 8, question: "Which metal is liquid at room temperature?", options: ["Iron", "Mercury", "Silver", "Gold"], answer: "Mercury", },
        { id: 9, question: "How many bones in adult human body?", options: ["206", "210", "208", "201"], answer: "206", },
        { id: 10, question: "Which gas is used in balloons?", options: ["Helium", "Oxygen", "Nitrogen", "Hydrogen"], answer: "Helium", },
    ],

    logicalQuestions: [
        { id: 1, question: "Ravi’s mother has a brother. That brother has a son, Ajay. What is Ajay to Ravi?", hindi: "रवि की माँ का एक भाई है। उस भाई का एक बेटा है अजय। अजय, रवि का क्या लगता है?", options: ["Cousin", "Uncle", "Brother", "Nephew"], answer: "Cousin", },
        { id: 2, question: "Neha is the daughter of my mother’s sister. What is Neha to me?", hindi: "नेहा मेरी माँ की बहन की बेटी है। नेहा मेरे लिए क्या हुई?", options: ["Sister", "Cousin", "Niece", "Aunt"], answer: "Cousin", },
        { id: 3, question: "A is B’s father’s son. How is A related to B?", hindi: "A, B के पिता का बेटा है। A, B का क्या लगता है?", options: ["Uncle", "Brother", "Cousin", "Father"], answer: "Brother", },
        { id: 4, question: "If Priya is the sister of Ramesh, and Ramesh is the father of Arjun, what is Priya to Arjun?", hindi: "अगर प्रिया रमेश की बहन है और रमेश अर्जुन का पिता है, तो प्रिया अर्जुन की क्या हुई?", options: ["Aunt", "Mother", "Sister", "Cousin"], answer: "Aunt", },
        { id: 5, question: "Rohan’s mother’s husband’s father is?", hindi: "रोहन की माँ के पति के पिता कौन हुए?", options: ["Grandfather", "Uncle", "Father", "Brother"], answer: "Grandfather", },
        { id: 6, question: "If A is the brother of B and C is the sister of B, what is A to C?", hindi: "यदि A, B का भाई है और C, B की बहन है, तो A, C का क्या हुआ?", options: ["Brother", "Cousin", "Uncle", "Father"], answer: "Brother", },
        { id: 7, question: "Manu is the only son of his grandfather. How is Manu related to his uncle’s daughter?", hindi: "मनु अपने दादा का इकलौता बेटा है। वह अपने चाचा की बेटी का क्या लगता है?", options: ["Cousin", "Brother", "Nephew", "Uncle"], answer: "Cousin", },
        { id: 8, question: "If ‘father + mother = parents’, then what is ‘uncle + aunt’?", hindi: "अगर ‘पिता + माँ = माता-पिता’, तो ‘चाचा + चाची = ?’", options: ["Relatives", "Couple", "Family", "Elders"], answer: "Relatives", },
        { id: 9, question: "Rita's father is Anil, and Anil is the only son of Suresh. How is Suresh related to Rita?", hindi: "रीता का पिता अनिल है, और अनिल सुरेश का इकलौता बेटा है। सुरेश रीता के क्या हुए?", options: ["Grandfather", "Uncle", "Father", "Brother"], answer: "Grandfather", },
        { id: 10, question: "If Ram is the brother of Shyam, and Shyam is the brother of Mohan, then Ram is the ___ of Mohan?", hindi: "अगर राम, श्याम का भाई है और श्याम, मोहन का भाई है, तो राम, मोहन का क्या हुआ?", options: ["Cousin", "Brother", "Uncle", "Father"], answer: "Brother", },
    ]
}